### ISSUE TITLE
Bug in Inductive Miner

### ISSUE THREAD

**Issue by s-j-v-zelst** [pm4py/pm4py-source#14]
I found another bug in the inductive miner.
On the simple log [<b,c,e,j>, <b,d,j>, <f,h,g,i,k>] (attached a .txt (remove it to get the .xes)
[pm4py_imdf_issue.xes.txt](https://github.com/pm4py/pm4py-source/files/2538025/pm4py_imdf_issue.xes.txt)
), the IM fails to recognize the xor construct between c,e and d.

I have attached a log that contains the data, the output of the IM in pm4py, and the output of the same miner (dfg based) from ProM.

Please fix (ASAP!), because this is a rather severe problem and should not be in the release.

![pm4py_imdf_correct](https://user-images.githubusercontent.com/6236151/47845709-00b62400-ddc6-11e8-99ec-186b49d4a649.png)
![pm4py_imdf_issue](https://user-images.githubusercontent.com/6236151/47845710-00b62400-ddc6-11e8-93e1-c061dccdad40.png)

**Comment by Javert899** [comment]
Thank you for signaling.

Actually the problem was in sequential cut detection, that has now been refined.
The problem spotted in your log is solved and the process extracted is the following:

![test1](https://user-images.githubusercontent.com/41383598/47847404-69ec6600-ddcb-11e8-9ee9-8e7245f5ef0c.png)

Please check if the problem is actually resolved

**Comment by s-j-v-zelst** [comment]
looks great!
I'll test it in my code and close the issue.
good to see that we are both "hobbying" on a free day :-)
