### ISSUE TITLE
Proposed Names Change: TraceLog -> EventLog, EventLog -> EventStream

### ISSUE THREAD

**Issue by s-j-v-zelst** [pm4py/pm4py-source#41]
After some discussion with some people "in the community".

I was requested to rename TraceLogs to EventLogs (as this is what they really are) and to rename EventLogs in PM4Py to something else.
In that sense, the EventLogs in PM4Py are equal to (finite) Event Streams in numerous academic articles.

I therefore to propose to do the renaming/refactoring ASAP:
-> EventLog -> EventStream
-> TraceLog -> EventLog

**Comment by fmannhardt** [comment]
Just some unsolicited thoughts on the design of event logs in PM4PY, which maybe come to late and without knowing much of the Python background.

Have you considered taking a little bit more radical view on `EventLogs` or `EventStream` and simply storing them as a data frame in which the columns are attributes and the rows are events? This would probably benefit from optimized storage solutions for column-based data frames.

The traces can be easily obtained by sorting on the case column, so the (probably inefficient) list of lists data structure is not strictly needed as this could be provided transparently as a `view` on top of a sorted data frame. Resorting data frames is probably also available as efficient operation.

Downside of it is that attributes cannot have attributes, the old meta-attributes issue, which I was fighting when designing XESLite for ProM. This can be solved in several ways:
1. just ignore meta attributes; 
2. keep objects instead of primitives, not sure if this is supported by pandas and this would probably sacrifice most of the optimizations possible;
3. try to create additional sparse data frames for each meta-attribute (only one level).

Does this make sense?

**Comment by s-j-v-zelst** [comment]
Hi Felix, this relates to #44 
I think it is a good idea, yet somehow either:
   - using interfaces
   - create a sort of separate PandasLog class that is in general supported by most algorithms in PM4Py

**Comment by Javert899** [comment]
Hi,

The proposed changed has been done in the 'develop' branch
