### ISSUE TITLE
Inductive Miner Cut Maximization

### ISSUE THREAD

**Issue by s-j-v-zelst** [pm4py/pm4py-source#43]
The inductive miner uses cuts of maximal size 2 rather than maximizing a found non-maximal cut.

We need to fix this (fast) as we (expect to) not have perfect replay fitness guarantees because of this.

**Comment by Javert899** [comment]
Hi,

A new version of Inductive Miner, namely IMDFB, has been introduced and made default in the 'develop' branch:
- the sequence cut follows the original implementation, found in org.processmining.plugins.InductiveMiner.mining.cuts.IM.CutFinderIMSequence.findCut(Dfg), that finds the strongly connected components of the DFG and orders them according to the direction. According to that implementation, a maximal cut is found.
- parallel cut has been fixed and can manage more complex situations like:
![image](https://user-images.githubusercontent.com/41383598/52197163-d2c9fb00-285e-11e9-9ee5-9d35b7f3601a.png)
- the loop cut follows almost the original implementation, found in org.processmining.plugins.InductiveMiner.mining.cuts.IM.CutFinderIMSequence.findCut(Dfg), with the difference that the start and the end activities are inferred from the DFG (since we have not the sublogs).

In comparison to the old approach, precision has generally improved (on the left, IMDFA; on the right, IMDFB):

01_running-example.xes.gz 100.0 0.3107344632768362 100.0 0.5092592592592593
02_teleclaims.xes.gz 100.0 0.1845569516430755 100.0 0.13452226018735258
03_repairExample.xes.gz 100.0 0.21876224792970478 100.0 0.24579172407915106
04_reviewing.xes.gz 100.0 0.17672741078208054 100.0 0.28504072010287185
05_bpic2017.xes.gz 100.0 0.7624603241089796 100.0 0.7596193436627137
06_bpic2013_incidents.xes.gz 100.0 0.3669301660337906 100.0 0.39910698952430024
07_bpic2013_problems.xes.gz 100.0 0.6143437077131259 100.0 0.6143437077131259
08_receipt.xes.gz 100.0 0.12407521080347628 100.0 0.12407521080347628

There are some important remarks to do:
- in a32f0n00.xes syntethic log, some difficulties were there with the DFG, since a parallel cut between activities "g" and "h9" was detected, while a loop cut shall be detected. Indeed, the problem was that "h9" is not directly connected to any activity preceding the given part. So, a further check is done on parallel cuts to check if they connect correctly to the other parts of the model.
- in a32f0n00.xes synthetic log, the original algorithm of sequential cut detection (that is kept) produces at some point the following cut: [['b'], ['c'], ['d'], ['e'], ['j']], that is not very precise and constrain the model to contain many hidden transitions, but that is.
- the algorithm that adds invisible transitions to the tree is overly prudent, so in the tree a lot of hidden transitions appear, although in the final Petri net a reduction mechanism is deployed in order to remove the hidden transitions that are not useful.
