### ISSUE TITLE
Petri net importer returns empty petri net object on attached .pnml file

### ISSUE THREAD

**Issue by d4rty** [pm4py/pm4py-source#80]
[CCC19 - Model PN.zip](https://github.com/pm4py/pm4py-source/files/3211229/CCC19.-.Model.PN.zip)

**Comment by Javert899** [comment]
Hi, probably you are working with an old release of PM4Py, since no problems seems to be there in the current one

I concurred in the CCC19 using PM4py

There is a slight unconformance in the way the invisible transitions are expressed as INVISIBLE in the label, but that you could solve by some little change to the importer as preprocessing step :) or after importing the net
