### ISSUE TITLE
Exception is thrown when I want to decorate perti net graph with frequency information

### ISSUE THREAD

**Issue by MehdiGol** [pm4py/pm4py-source#97]
I face an exception when I want to decorate perti net graph with frequency or performance information.
When I add variant = 'frequency' to this function

pn_vis_factory.apply(net, initial_marking, final_marking, parameters=parameters,variant='frequency', log=log)

I get this exception:

unsupported operand type(s) for -: 'str' and 'str'

Any kind of help would be greatly appreciated.

**Comment by Javert899** [comment]
Hi, thanks for signaling

Any further information, e.g. The log that you are trying to use, or information like the type (XES, CSV, Parquet?), the process discovery algorithm that you apply, can be useful

Your issue will be worked before Monday

**Comment by MehdiGol** [comment]
The log is an XES file, and the algorithm is inductive_miner.
Thank you so much for your consideration...

**Comment by Javert899** [comment]
I have done some tests to replicate your problem.

The replication was possible only when the time:timestamp attribute of the events is a "string" instead of a "datetime" object.

To verify my claim, you could run the following code to check the type of the time:timestamp attribute of the first event:

print(type(log[0][0]["time:timestamp"]))

If it is string, here you have a problem.

When you have such problem, only way to overcome it is to parse the string. May be the easiest way to do that:


from dateutil import parser
for trace in log:
    for event in trace:
        event["time:timestamp"] = parser.parse(event["time:timestamp"])

**Comment by MehdiGol** [comment]
You were right,

The problem was my timestamp format and fixed it.

Thank you so much...
